### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by SiddharthaKostiRaga**
This PR implements error handling for various scenarios in authentication and project management processes. The changes address the following cases:

1. Authentication Failure
2. Invalid Project Name in Tracing
3. Inaccessible Base URL
4. Schema Mismatch for Trace Logging
5. Duplicate Experiment Name for Project

**Implemented Error Messages**

- Authentication Failure: "Authentication failed. Navigate to Settings -> Authentication to generate new Secret key and Access key"
- Invalid Project Name: "Project not found. Please enter a valid project name"
- Inaccessible Base URL: "The provided base_url is not accessible. Please re-check the base_url"
- Schema Mismatch: "Trace cannot be logged to this Project because of schema difference. Create a new project to log trace"
- Duplicate Experiment Name: "The experiment name already exists in the project. Enter a unique experiment name."

### CODE REVIEW

**Comment by Ritika1311** [comment]
1-In 1st task when giving the incorrect access key or secret key but the base url is correct - it is giving error `ConnectionError: The provided base_url is not accessible. Please re-check the base_url.` @SiddharthaKostiRaga @kiran-raga

**Review by Ritika1311 — CHANGES_REQUESTED** [review]
when access key and secret key is incorrect but base url is correct , it is giving me error - `ConnectionError: The provided base_url is not accessible. Please re-check the base_url.` @SiddharthaKostiRaga @kiran-raga

**Review by Ritika1311 — CHANGES_REQUESTED** [review]
now getting error on correct access key and secret key. @SiddharthaKostiRaga

**Comment by kiran-raga** [comment]
Issues resolved

**Pull request merged**
